{{- if .Values.connectionSecret.create }}
{{- $reflector := include "ack-opensearch-provider.reflectorAnnotations" . | trim }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ack-opensearch-provider.connectionSecretName" . }}
  labels:
    {{- include "ack-opensearch-provider.labels" . | nindent 4 }}
  {{- if or $reflector .Values.connectionSecret.annotations }}
  annotations:
    {{- if $reflector }}
    {{- $reflector | nindent 4 }}
    {{- end }}
    {{- with .Values.connectionSecret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  USERNAME: {{ .Values.auth.username | quote }}
  {{- if eq .Values.auth.mode "irsa" }}
  PASSWORD: ""
  {{- if .Values.auth.irsaRoleArn }}
  AWS_ROLE_ARN: {{ .Values.auth.irsaRoleArn | quote }}
  {{- end }}
  {{- end }}
{{- end }}
